using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using ShiftManager.Data;
using ShiftManager.Models;
using ShiftManager.Models.Support;
using ShiftManager.Models.Validation;
using ShiftManager.Resources;
using ShiftManager.Services;

namespace ShiftManager.Tests.Helpers;

/// <summary>
/// Test-only helper. Existing service tests (ChoreService, OnDutyService, ShiftAssignmentService)
/// pre-date the BusyService split — they exercise the OUTER auth/persistence logic and don't
/// care about busy detection. Mock.Of&lt;IBusyService&gt;() returns null on ValidateAsync, which
/// causes NREs when the outer service awaits the result. This factory returns a permissive
/// mock that always says "no errors, no warnings" so those tests can run unchanged.
///
/// Tests that DO want to verify busy semantics should use <see cref="Real"/> to construct
/// a real <see cref="BusyService"/> against the test's own in-memory DB. This is the same
/// wiring used by <see cref="ShiftManager.Tests.UnitTests.Services.BusyServiceTests"/>.
/// </summary>
public static class BusyServiceMockFactory
{
    public static IBusyService NoOp()
    {
        var mock = new Mock<IBusyService>();
        mock.Setup(s => s.ValidateAsync(
                It.IsAny<BusyTarget>(), It.IsAny<int>(), It.IsAny<int>(), It.IsAny<string?>()))
            .ReturnsAsync(new BusyValidation(true, Array.Empty<ValidationIssue>(), Array.Empty<ValidationIssue>()));
        mock.Setup(s => s.ValidateBatchAsync(
                It.IsAny<IReadOnlyList<(BusyTarget, int)>>(), It.IsAny<int>()))
            .ReturnsAsync((IReadOnlyList<(BusyTarget t, int u)> assignments, int _) =>
                assignments.ToDictionary(
                    a => a,
                    a => new BusyValidation(true, Array.Empty<ValidationIssue>(), Array.Empty<ValidationIssue>())));
        mock.Setup(s => s.GenerateOverrideToken(
                It.IsAny<BusyTarget>(), It.IsAny<int>(), It.IsAny<IReadOnlyList<string>>()))
            .Returns("test-override-token");
        mock.Setup(s => s.ValidateOverrideToken(
                It.IsAny<string?>(), It.IsAny<BusyTarget>(), It.IsAny<int>()))
            .Returns(true);
        mock.Setup(s => s.GetBusyStatesAsync(
                It.IsAny<IReadOnlyList<int>>(), It.IsAny<DateOnly>(), It.IsAny<int>(), It.IsAny<BusyTarget?>()))
            .ReturnsAsync(new Dictionary<int, BusySummaryWithHardError>());
        return mock.Object;
    }

    /// <summary>
    /// Constructs a real <see cref="BusyService"/> against the supplied DbContext.
    /// Use this for tests that exercise busy/conflict semantics.
    ///
    /// <para>
    /// The optional <paramref name="configuration"/> must share its <c>ApiKeyHmacSecret</c>
    /// with the outer service under test — otherwise override tokens generated by the outer
    /// service won't validate against this BusyService. When omitted a default test secret
    /// is used; pass the test's own IConfiguration when override-token round-trips matter.
    /// </para>
    /// <para>
    /// HierarchySettings defaults to <c>RestHours: 8, WeeklyCap: 56</c>. Override via
    /// <paramref name="restHours"/>/<paramref name="weeklyCap"/> to match the outer service's
    /// hierarchy mock — otherwise rest/cap assertions across the two services may diverge.
    /// </para>
    /// </summary>
    public static IBusyService Real(
        AppDbContext db,
        IConfiguration? configuration = null,
        int restHours = 8,
        int weeklyCap = 56)
    {
        var localizerMock = new Mock<IStringLocalizer<SharedResources>>();
        localizerMock.Setup(l => l[It.IsAny<string>()])
            .Returns((string key) => new LocalizedString(key, key));
        localizerMock.Setup(l => l[It.IsAny<string>(), It.IsAny<object[]>()])
            .Returns((string key, object[] args) => new LocalizedString(key, key));

        var hierarchyMock = new Mock<IHierarchySettingsService>();
        hierarchyMock.Setup(h => h.GetEffectiveSettingsAsync(It.IsAny<int>()))
            .ReturnsAsync(new EffectiveSettings(
                RestHours: restHours,
                WeeklyCap: weeklyCap,
                RestHoursSource: "Test",
                WeeklyCapSource: "Test"));

        var configCacheMock = new Mock<IAppConfigCacheService>();
        configCacheMock.Setup(c => c.GetConfigAsync(It.IsAny<int>(), It.IsAny<string>()))
            .ReturnsAsync((AppConfig?)null);

        IConfiguration cfg = configuration ?? BuildDefaultConfiguration();

        // Construct a real CompanyMembershipService against the same test DB so the
        // ~15 existing Real() callers do NOT need to change — the membership table will
        // simply be empty for tests that don't seed it, preserving backward-compatibility.
        var membershipService = new CompanyMembershipService(
            db,
            NullLogger<CompanyMembershipService>.Instance);

        return new BusyService(
            db,
            localizerMock.Object,
            NullLogger<BusyService>.Instance,
            hierarchyMock.Object,
            configCacheMock.Object,
            cfg,
            membershipService);
    }

    private static IConfiguration BuildDefaultConfiguration()
    {
        var configMock = new Mock<IConfiguration>();
        configMock.Setup(c => c["ApiKeyHmacSecret"]).Returns("test-busyservice-hmac-secret");
        return configMock.Object;
    }
}
